# Generated by Django 5.2.8 on 2025-11-10 15:17
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_author"),
    ]

    operations = [
        TrigramExtension()
    ]
